### ISSUE TITLE
To study the subject area and list the topics where Machine learning is used

### ISSUE THREAD

**Issue by yayakusheva** [GoAlexander/der_film#1]
- Alexander, Maxim 
- 2,5 wh *2
- priority: high

**Comment by GoAlexander** [comment]
1) Крутая разработка, но нет интеграции с другими сервисами. Не учитывает заранее известные предпочтения пользователя https://movix.ai/
Статья о них на медиуме https://medium.com/deep-systems/movix-ai-movie-recommendations-using-deep-learning-5903d6a31607
2) Статья. Анализировали сценарий сюжета с помощью алгоритмов NLP, строили "кривую" сюжета. https://techxplore.com/news/2018-07-machine-analyse-movie.html
3) Using AI to understand the way a movie “looks” and “sounds” like https://medium.com/behavioral-signals-ai/using-ai-to-understand-the-way-a-movie-looks-and-sounds-fe931d487171
4) CONVOLUTIONAL COLLABORATIVE FILTER NETWORK FOR VIDEO BASED RECOMMENDATION SYSTEMS https://arxiv.org/pdf/1810.08189.pdf
5) The 4 Recommendation Engines That Can Predict Your Movie Tastes - оч интересно. https://medium.com/@james_aka_yale/the-4-recommendation-engines-that-can-predict-your-movie-tastes-bbec857b8223
6) Machine Learning for Recommender systems — Part 1 https://medium.com/recombee-blog/machine-learning-for-recommender-systems-part-1-algorithms-evaluation-and-cold-start-6f696683d0ed 
7) Creating a movie recommender using Convolutional (свёрточные) Neural Networks https://towardsdatascience.com/creating-a-movie-recommender-using-convolutional-neural-networks-be93e66464a7
8) Comprehensive Guide to build a Recommendation Engine from scratch https://www.analyticsvidhya.com/blog/2018/06/comprehensive-guide-recommendation-engine-python/
9) Netflix Analytics - Movie Recommendation through Correlations / CF (есть код))) - https://www.kaggle.com/laowingkin/netflix-movie-recommendation
10) Movie Recommender Systems (код) - https://www.kaggle.com/rounakbanik/movie-recommender-systems
TODO?: Прошерстить kaggle на наличие подобных проектов, если будут нужны примеры

**Comment by GoAlexander** [comment]
Результат, сообщество использует машинное обучение для:
- рекомендательных систем
- оценки успешности будущего фильма (рейтинг) (реже и менее распространнено)
