### ISSUE TITLE
[research] Кластеризация фильмов

### ISSUE THREAD

**Issue by GoAlexander** [GoAlexander/der_film#13]
Настя
5wh

**Comment by LupusSanctus** [comment]
IMDB films extracting and clusterization (scikit) on the basis of marked from plot words (their frequency, value-weight). In future it may be applied to film clusters identification for specified user/groups of users (in accordance with his/her profile details) - clusters and users mapping.

**Comment by LupusSanctus** [comment]
Made clusterization with Latent Dirichlet allocation method (LatentDirichletAllocation). Max groups number is 85, min 10.
