### ISSUE TITLE
Нарисовать диаграмму по расположению

### ISSUE THREAD

**Issue by GoAlexander** [GoAlexander/der_film#15]
5wh

**Comment by yayakusheva** [comment]
[https://www.draw.io/?lightbox=1&highlight=0000ff&edit=_blank&layers=1&nav=1&title=architecture.html#R7Vrbcps6FP0az7QPyQDi5kcndi8zPXN6Juk0eerIRrZpMaJCru1%2B%2FZFA4iLAwY1wPU3zErQRkqy99toXaQRuN%2Fu3BCbrf3CAopFlBPsRmI4syzKBx%2F5xySGXjG0jF6xIGOSiiuAu%2FIlyoSml2zBAqZDlIopxRMOkLlzgOEYLWpNBQvCu3m2Jo6AmSOAKNQR3Cxg1pZ%2FDgK5zqe8YpfwdCldrObNpiDdzuPi2Ingbi%2FlGFlhmf%2FnrDZRjif7pGgZ4VxGB2QjcEoxp%2FrTZ36KI72192950vC3WTVBM%2B3xgvY2s6cPsa%2Bje%2F3tvf1jD2e1%2FVyAf5QeMtkj%2BjGyx9CA3CAVsv0QTE7rGKxzDaFZKb7JNQHwag7XWdBOxR5M9fkWUHoTK4ZZiJipH%2BIBxIvqxX0AOD%2BL7rPHIG9eObE731ZfTg2jla%2BUL7NwTIUrxlizQkY2Q0INkheiRfk6hOWYRCG8QWw%2F7jqAI0vBHfR1QQHNV9Cs%2B%2FYhDtkLLkGYkQSWMyPaUIfJ1ia9KJU8IgYdKt4R3SLvnMX23Po%2Fv1zFzWn%2F2kK9Atip7UooyHJ6ASbMFk27ElHKzxNniSnC637dYvrhKM6BNWAfTT%2FblS%2Fa04v%2FfxxSRmGlXjMYWlw%2BYv24CP4oYCXGAM9NNuHAR4S1b%2Bc1uHVJ0l8AMUTvGi3XYi%2FUjQtH%2BODCbQJIfeNdOfeftQrIracqU5LKuUJRvdMOvornTFTP%2BSxYVEuhBFt4wZOHWoeGCAhqa6UKdybPOYP7OQOY%2F21MCF4wCmABuuMnG8zTJO2TDz0lJBXolDaZpdlTsqG4lw%2FONZSh0Y5j9yMb0wEBs4w6Eg09JAHMU9PICZ9eEaavU77dSv9RQVRu2N5AyTKuhDQJ3X9hOQp0%2BAO1D%2BlB5zpkdiFZJ7Lwheb30B6ULeKz6ig5%2F0NffaPQbXk%2B%2FYRrtEDnNcZzK9o4L6mxvnCPYc7XiZ2AstOPTO4rP34EfMEjgYfv1LMXzFbrJf8Czww7bUcIOQWtdWUqRrLf3Hwa4lt2fEZk3oHWgEsTcFJxnHThIxJaw3s7NyJkyCYzCVcxzDsTTFibgXiVcwGgiXmzCIMisIYJzFN0U1YhbHGGSzSvrEUf8kqiqiJWMimJFFZ1H7LbTi10x1nZEsijVIpT6qyCUXfBymSKqKFiLSr2BIo4pw8QcskyyZ8gh002OpZRigs4SeACF%2Fl1p7ZWgY2w1Y47xYDGHM3xo4TlHufs3xAh6fH%2BDI71xnSMdGdFpThld02%2Bdp4u7u9Y1LHc3o9llGG2%2BhEH6Iri7o4hZcrcLPK3cLSnGqg1qq2WL4ahdnjZo5%2FYJI4LDz%2F7p5BM8DtMkP%2BRYhnvOYjqI3TF8NaMEoEHtpjFucnsh1E7u1lBlnnsCw%2Fiy9WF5NW0Asy2%2F91pcrZTpd7XeEK7WuDaAksmD4%2F62yN%2BKhC3%2FznqquHtKAvcRkZBtGydm7adIwq6Gz%2FCfpW7QyobCkN6zF1H4jUWrBneKNQtTypbCafaoZ%2F6JXrSjul96UcazdUu3nudFz%2BAm286DdbDyZzRPGdH2KZpzPaK4FVR%2Fdg1eDYUvoAYvg3ndfkF6gceqEzipulu6gIup7pp2T%2FLXcofg5KN%2FQznMs0S%2B35WZqYd%2FSv%2BBMrPm4f%2BnJOAHNkyY19aMVyPw5nXTfl8RdEV58Mc3RUTlr5tnfS%2FAMflHaca4NsfKtQ55DehyHVNxieqsVw36koP2ao1pKOexjtmv1N4YaWyq9RVlIF03i7pWfOrChj1tahbtzx7fvLzApoGNS4hsxkNENvVs17q84vIwB4NNBbvKHTRNLKOShpyn8%2F5i18IGZRnQVttSwRYHE357mYcREUzTcME0nbJtok2xhgPuXwm9deJOqO3J0NjqiI0rROG08ISUPfeAWzkCs%2BXthFO9rmPWBwKuMlCHPTyNQNYsr4zn3ct7%2BWD2Pw%3D%3D](url)

**Comment by yayakusheva** [comment]
https://www.draw.io/#G1SF8kDab-rG8CANwDysPDqQ2-OLgySZQR

**Comment by GoAlexander** [comment]
Need Google Drive authorization (in your account)

**Comment by yayakusheva** [comment]
![img_0007](https://user-images.githubusercontent.com/46791107/52784195-5658c880-3065-11e9-8652-02f71fc1dfda.png)

**Comment by yayakusheva** [comment]
![img_0008](https://user-images.githubusercontent.com/46791107/52784206-607ac700-3065-11e9-8ed5-c8bc553cca49.png)
