### ISSUE TITLE
To choose tools for future analysis

### ISSUE THREAD

**Issue by yayakusheva** [GoAlexander/der_film#2]
- Alexander, Maxim
- 2 wh *2
- priority: high

**Comment by GoAlexander** [comment]
В соответствии с выполненным анализом конкурентов наш проект будет в области:
- рекомендательная система

Если останется много времени, то сделаем:
- предсказание рейтинга
- предоставим api

Технологии и языки (список может быть изменен во время работы):
- Python
- Tensorflow
