### ISSUE TITLE
[rating] Улучшения нейронки

### ISSUE THREAD

**Issue by GoAlexander** [GoAlexander/der_film#21]
Phase 1:
- [x] запушить код в гитхаб @Maxitet 

Phase 2:
- [x] добавить ключ для предсказания из кеша и построения кеша
- [x] Вывести обучение отдельным скриптом
- [x] Добавить вывод результатов (film_ids) в виде print и в виде json

**Comment by adydychk** [comment]
> Добавить вывод результатов (film_ids) в виде print и в виде json

Done

**Comment by adydychk** [comment]
Server prepared for rest api server.  
All credentials sent through private message
