### ISSUE TITLE
Подготовить use-case диаграммы

### ISSUE THREAD

**Issue by GoAlexander** [GoAlexander/der_film#22]

**Comment by yayakusheva** [comment]
![usecase1](https://user-images.githubusercontent.com/46791107/53128074-04d4a000-3575-11e9-9d98-82cb13d3e8ec.png)

use-case diagram #case1
Пользователь, который заходит на сайт, дает ссылку на свой профиль кинопоиска, после чего система анализирует его профиль и производит "предсказание" – какой бы этот человек, судя по его профилю, дал бы рейтинг какому то n множеству фильмов (вопрос, как это множетство будет выбираться, еще не решен). После проведенного анализа мы система выдает ему те фильмы, у которых наибольший "рейтинг".

**Comment by yayakusheva** [comment]
![usecase2](https://user-images.githubusercontent.com/46791107/53128101-1a49ca00-3575-11e9-8aa0-0300f23f9065.png)

use-case diagram #case2
Пользователь заходит на сайт, где выбирает те фильмы, которые ему нравятся. Система анализирует выбранные им фильмы и подбирает из бд похожие, после чего дает пользователю рекомендации.

**Comment by yayakusheva** [comment]
![usecase3](https://user-images.githubusercontent.com/46791107/53128508-08b4f200-3576-11e9-9a79-c3baa23b9720.png)

use-case #case3
Пользователь, зашедший на сайт, выбирает ключевые слова, по которым система в бд ищет соответствующие фильмы. Далее система ранжирует выбранные фильмы в соответствии с тем, насколько сильно они подходят выбранным ключевым словам и выводит пользователю самые подходящие как результат.
