### ISSUE TITLE
[key word] Улучшение алгоритма

### ISSUE THREAD

**Issue by GoAlexander** [GoAlexander/der_film#23]
Если пользователь заходит, например, выбирает слова ключевые (которые по сути составляют плот), пусть он выберет макс число слов штуки 4, а оставшееся тогда спрогнозируется (чтобы не предлагать пользователю час тыкать, например, а чтобы оно достроило логический ряд само,а затем выбрало нужный кластер)

5wh

**Comment by LupusSanctus** [comment]
**Phase1** - представленно несколько моделей:
1) Первая модель - подавая на вход одно слово, модель будет выдавать следующее (в 
 рамках исходной последовательности слов, используемой для обучения).
Модель использует изученые слова, предложенные на входном слое сети. Есть вектор для каждого слова в словаре, если входная последовательность содержит одно слово, тогда input_length=1.
У модели есть единственный LSTM (Long short-term memory) слой с 50-ю юнитами. Выходной слой состоит из одного нейрона для каждого слова в словаре и использует softmax-функцию для проверки того, что выходные значения нормализированны и являют собой вероятностные.

2) Вторая модель (по реализации не сильно отличается от первой) - подаём на вход несколько слов, на выход будем получать оставшуюся последовательность.

**Phase 2: TBD:** 
объединение функций кластеризации и текущих моделей. Переработка методов с учётом подачи кластеров плота на вход и массива слов пользователя (3-4 слова - оставшаяся цепочка прогнозируется - уже реализовано), представить в качестве выходов соответствующие фильмы из кластеров.
