### ISSUE TITLE
Провести опрос качества предсказания скрипта на пользователях

### ISSUE THREAD

**Issue by GoAlexander** [GoAlexander/der_film#25]

**Comment by GoAlexander** [comment]
![image](https://user-images.githubusercontent.com/13280035/53576572-0b6ea300-3b85-11e9-80d0-8094b180f8b4.png)

**Comment by yayakusheva** [comment]
[Опрос пользователей по качеству работы системы.docx](https://github.com/GoAlexander/der_film/files/2941949/default.docx)

**Comment by yayakusheva** [comment]
Итог на данный момент:
Из 23х опрошенных 16, т.е. примерно 70 %, удовлетворены полученными от системы рекомендациями.
