### ISSUE TITLE
[key word] Улучшение алгоритма №2

### ISSUE THREAD

**Issue by GoAlexander** [GoAlexander/der_film#26]
Phase 2:
объединение функций кластеризации и текущих моделей. Переработка методов с учётом подачи кластеров плота на вход и массива слов пользователя (3-4 слова - оставшаяся цепочка прогнозируется - уже реализовано), представить в качестве выходов соответствующие фильмы из кластеров.

**Comment by LupusSanctus** [comment]
Функция по разбивке групп кластеров на подкластеры+прогноз:
https://github.com/GoAlexander/der_film/blob/master/Analyse%20Engine/forecasting_words_line_PHASE2.ipynb

**Comment by LupusSanctus** [comment]
Получение фильмов из спрогнозированной линии плота (по нескольким входным словам - в будущем предполагается, что пользовательским):
https://github.com/GoAlexander/der_film/blob/master/Analyse%20Engine/forecasting_words_line_PHASE2.ipynb
