### ISSUE TITLE
Функция для дампа использованных переменных и RMSE

### ISSUE THREAD

**Issue by GoAlexander** [GoAlexander/der_film#34]

**Comment by GoAlexander** [comment]
https://github.com/GoAlexander/der_film/blob/master/deep_learning/film_learner.py#L26

https://github.com/GoAlexander/der_film/blob/master/deep_learning/film_learner.py#L16

https://docs.google.com/presentation/d/12XlVnbHt4lLAaSVDvlM1Yw4Ee_qChi1BMCMsGlexi4U/edit#slide=id.g562c10a10b_0_17

**Comment by adydychk** [comment]
https://github.com/GoAlexander/der_film/blob/master/deep_learning/film_learner.py#L116
