### ISSUE TITLE
[key_word] Перейти на новые данные для анализа

### ISSUE THREAD

**Issue by GoAlexander** [GoAlexander/der_film#42]

**Comment by Maxitet** [comment]
http://goalexander.asuscomm.com:8000/forecasting-words?viewCluster=yes&maxGroupNumber=80&cluster=4&clusterId=1&wordsNumber=4
http://goalexander.asuscomm.com:8000/film-clust?viewCluster=true&maxGroupNumber=10&clusterType=3
