### ISSUE TITLE
The functional requirements for outcoming data

### ISSUE THREAD

**Issue by yayakusheva** [GoAlexander/der_film#5]
- Victoria
- 2 wh
- priority: high

**Comment by GoAlexander** [comment]
- список id\`шников фильмов в порядке убывания соответствия

**Comment by yayakusheva** [comment]
Для задач

**Comment by yayakusheva** [comment]
Для задачи предсказания рейтинга:
+ список id фильмов в порядке убывания рейтинга

**Comment by yayakusheva** [comment]
1. Список выводится на новой странице
2. Список выводить по убыванию
3. Каждая строка списка содержит порядковый номер и название фильма 
4. При нажатии на название открывается ссылка на информацию о фильме 
5. Возможность сохранить список (уточняется необходимость)
