### ISSUE TITLE
Проанализировать методы/ способы реализации рекомендательных систем

### ISSUE THREAD

**Issue by GoAlexander** [GoAlexander/der_film#8]
5 wh

**Comment by yayakusheva** [comment]
Основные алгоритмы, применяемые в рекомендательных системах, это:
- Summary-based
- Content-based
- Collaborative filtering (user based)
- Collaborative filtering (item based)
- Matrix factorisation
- и другие подходы 

Полную информацию по всем методам можно посмотреть в файле «Методы и способы рекомендательных систем»

**Comment by yayakusheva** [comment]
На практике редко используется только один подход. Для достижения максимального эффекта несколько подходов комбинируются в один. 
Два главных преимущества объединения моделей — это увеличение точности и возможность более гибкой настройки на разные группы клиентов. Недостатки — меньшая интерпретируемость и бОльшая сложность реализации и поддержки.

**Comment by yayakusheva** [comment]
В центре любой рекомендательной системы находится так называемая матрица предпочтений. Это матрица, по одной из осей которой отложены все клиенты сервиса (Users), а по другой – объекты рекомендации (Items). На пересечении некоторых пар (user, item) данная матрица заполнена оценками (Ratings) – это известный нам показатель заинтересованности пользователя в данном товаре, выраженный по заданной шкале (например от 1 до 5).

**Comment by yayakusheva** [comment]
Основные алгоритмы, применяемые в рекомендательных системах, это:
- Summary-based
- Content-based
- Collaborative filtering (user based)
- Collaborative filtering (item based)
- Matrix factorisation
- и другие подходы 

Полную информацию по всем методам можно посмотреть в файле «Методы и способы рекомендательных систем»

**Comment by yayakusheva** [comment]
На практике редко используется только один подход. Для достижения максимального эффекта несколько подходов комбинируются в один. 
Два главных преимущества объединения моделей — это увеличение точности и возможность более гибкой настройки на разные группы клиентов. Недостатки — меньшая интерпретируемость и бОльшая сложность реализации и поддержки.
